application: pcf-2016-frontend
module: frontend
version: 1
api_version: 1
runtime: python27
threadsafe: yes

handlers:
- url: /
  static_files: assets/templates/searchMap.html
  upload: assets/templates/searchMap.html

- url: /assets
  static_dir: assets



  # - url: /icons
  #   static_dir: assets/icons

  # - url: /images
  #   static_dir: /assets/images

  # - url: /js/*
  #   static_dir: assets/js 
